### ISSUE TITLE
Add in-session bells

### ISSUE THREAD

**Issue by djibux** [wlach/meditation#1]
Hello.

I would love the ability to have "in-session" bells to split a meditation in different parts. For instance I might want to split a meditation in three having the first part on body awareness, the second on sounds and the third on thoughts.

I hope you like the idea and find some time to implement it.  Thanks for your app.

**Comment by wlach** [comment]
Hey, I think I'm going to pass on this idea in the interests of keeping things simple. Thanks for the suggestion though. :)
